version: "3.8"

services:

   difference:
        build: .
        image: web_deepcopy:latest
        mem_limit: 512m
        cpus: 0.5
        storage_opt:
              size: 1G
        hostname: web_deepcopy
        container_name: web_deepcopy
        networks:
           challenge_net:
        restart: unless-stopped
networks:
  challenge_net:
    name: chal_subnet
    external: true
