version: "3.8"

services:

   difference:
        build: .
        image: web_template:latest
        mem_limit: 512m
        cpus: 0.5
        storage_opt:
              size: 1G
        hostname: web_template
        container_name: web_template
        networks:
           challenge_net:

networks:
  challenge_net:
    name: chal_subnet
    external: true
